import { Hammer, HardHat, KeyRound, Leaf, PaintRoller, PlugZap, Snowflake, Wrench } from "lucide-react";
import { tradeImages } from "@/lib/mock-data";

export const brandName = "Artizan Moris";
export const allTradesLabel = "All trades";
export const allDistrictsLabel = "All districts";
export const allTagsLabel = "All tags";

export const marketplaceCopy = {
  en: {
    nav: { postJob: "Get help today", login: "Login", artisan: "Are you an artisan?" },
    hero: {
      location: "Made in Mauritius",
      eyebrow: "Find a trusted artisan in Mauritius — today",
      headlineLead: "Get it fixed by a",
      headlineEm: "trusted local artisan",
      headlineTail: ".",
      support:
        "Describe what's wrong, we find a verified artisan near you, and they contact you on WhatsApp. No more calling five people hoping one picks up.",
      ctaPrimary: "Describe your problem — we'll find someone today",
      ctaSecondary: "How it works",
      chips: ["Verified artisans", "Contact on WhatsApp", "EN / FR / Kreol", "Same-day"],
      visualBadge: "Verified",
      visualCaption: "Your neighbour's plumber, one tap away",
    },
    how: {
      title: "How Artizan Moris works",
      subtitle: "Three steps, and no more chasing contractors all afternoon.",
      steps: [
        { title: "Describe the job", desc: "Two sentences and a quick photo from your phone — that's it." },
        { title: "Get matched with verified artisans", desc: "We notify artisans near you who do exactly that kind of work." },
        { title: "Chat & book on WhatsApp", desc: "Chat directly on WhatsApp, agree a time that suits you both, done." },
      ],
    },
    tradesSection: {
      title: "Popular trades",
      subtitle: "Tap what you need — we'll take it from there.",
    },
    request: {
      eyebrow: "Start here",
      title: "Tell us what you need",
      subtitle: "Post once, sit back. Verified artisans reach out to you on WhatsApp — at no cost.",
    },
    why: {
      title: "Why Artizan Moris",
      items: [
        { title: "Verified artisans", desc: "Every artisan is identity-checked before they show up on the platform." },
        { title: "Local to Mauritius", desc: "Built for Mauritius — the districts, the trades, and yes, WhatsApp, because that's how we all communicate." },
        { title: "No more weekend ruined chasing a plumber", desc: "One clean request reaches the right artisans for you." },
        { title: "Free to post", desc: "Free to post, always. You only talk to artisans you've actually chosen." },
      ],
    },
    browse: {
      eyebrow: "Browse artisans",
      title: "Verified artisans",
      subtitle: "Filter by trade, area and service. Verified profiles appear first.",
      filters: "Filters",
      quickTitle: "Quick starts",
      filterAction: "Filter results",
      resetAction: "Reset",
      searchPlaceholder: "Leak, wiring, AC, cabinet...",
      fastFirst: "Fast first",
      readyHeading: (n: number) => `${n} ${n === 1 ? "artisan" : "artisans"} ready`,
      sortedEta: "Sorted by ETA",
      verifiedFirst: "Verified first",
      availableNow: (n: number) => `${n} available now`,
      onboarding: "More verified artisans joining every week",
      fastestEta: (n: number) => `${n} min fastest ETA`,
      etaSoon: "ETA appears when matches are live",
      reviewAfter: "Review your artisan after the job",
      allVerified: "All verified artisans",
      emptyTitle: "We're still building up in your area",
      emptyCopy:
        "We're signing up verified artisans across the island right now. Post your job and we'll connect you the moment someone becomes available in your area.",
      emptyCta: "Post your job",
      view: "View",
      selected: "Selected",
      available: "Available",
      later: "Later today",
      verified: "Verified",
      portfolio: "Portfolio",
      portfolioEmpty: "Portfolio photos will appear here after this artisan uploads verified work.",
      reviews: "Reviews",
      reviewsCount: (n: number) =>
        n
          ? `${n} public reviews recorded. Detailed comments appear once review storage is connected.`
          : "No public reviews yet.",
      availability: "Availability",
      availableToday: (n: number) => `Available today. Estimated response: ${n} min.`,
      notAvailable: "Not marked available right now. You can still prepare a request for later.",
      selectHint: "Send a WhatsApp-ready brief directly to this artisan.",
      whatsapp: "WhatsApp contact",
      whatsappBadge: "WhatsApp",
      callContact: "Call",
      reviewsNone: "No reviews yet — be the first to leave one.",
      leaveReview: "Leave a review",
      reviewName: "Your name",
      reviewNamePh: "e.g. Reshad",
      reviewRatingLabel: "Your rating",
      reviewComment: "Your review",
      reviewCommentPh: "How was the work?",
      reviewSubmit: "Submit review",
      reviewSubmitting: "Posting...",
      reviewThanks: "Thanks! Your review is posted.",
      noMatch: "No matches for these filters",
      noMatchHint: "Try fewer filters or a different search.",
    },
    faq: {
      title: "Good to know",
      items: [
        { q: "Is it free to post a job?", a: "Yes. Posting a job on Artizan Moris is completely free. You only arrange payment directly with the artisan you choose." },
        { q: "How do artisans reach me?", a: "Your WhatsApp number stays private. Artisans who accept your job contact you through a protected link — they never see your number directly." },
        { q: "Are the artisans verified?", a: "Every artisan is identity-checked before they can be matched to a job, and verified profiles are clearly badged." },
        { q: "Which areas do you cover?", a: "All of Mauritius, from Port Louis to Rodrigues. Just pick your closest area when you post." },
        { q: "What if no one is online yet?", a: "We're still growing in some areas. Post your job now — the moment a verified artisan comes online in your area, they'll see it first." },
      ],
    },
    footer: {
      tagline: "Your go-to for finding a reliable artisan anywhere in Mauritius.",
      cols: { product: "Product", company: "Company" },
      links: { post: "Post a job", browse: "Browse artisans", artisan: "Become an artisan", login: "Login" },
      contact: "Contact",
      builtFor: "Built for local service discovery",
    },
    bottomNav: { browse: "Browse", request: "Post job", artisan: "Artisan", login: "Login" },
    jobForm: {
      steps: ["Urgency", "Problem", "Location", "Contact"],
      badge: "Smart match",
      eyebrow: "Request",
      title: "Find an artisan",
      urgentTitle: "I need someone today",
      urgentDesc: "We'll find a verified artisan near you within the hour.",
      plannedTitle: "I'm planning ahead",
      plannedDesc: "Tell us the job and verified artisans near you will reach out.",
      describeLabel: "What's the problem?",
      describePlaceholder: "e.g. The kitchen sink has been leaking since this morning, water under the cabinet...",
      tradeLabel: "What kind of artisan do you need? (tap to change)",
      useLocation: "Use my location",
      locUnavailable: "GPS is not available here. Pick the closest area.",
      locShared: "Location shared. Choose the closest area so artisans can match faster.",
      locDenied: "No worries — just pick your area from the list below.",
      whatsappLabel: "WhatsApp number",
      privacy: "Your WhatsApp number stays private. Artisans only reach you through the app once they've accepted — you're in control.",
      addPhoto: "Add a photo",
      photoHint: "Optional — a quick photo helps artisans quote accurately",
      errUrgency: "Let us know if this is urgent — it changes how we match you.",
      errDescription: "A little more detail helps artisans come prepared — even a sentence works.",
      errDistrict: "Pick your area so we know which artisans are nearby.",
      errPhone: "Check your number — it should be a Mauritius mobile number starting with 5, 7, or 8.",
      errPhotoType: "Please choose an image file.",
      errPhotoSize: "That photo is a bit big. Try a screenshot or reduce the size — anything under 5 MB works.",
      errPost: "Request could not be posted.",
      errFailed: "Something went wrong on our end. Your details are saved — tap to try again.",
      back: "Back",
      continue: "Continue",
      submitUrgent: "Send my request now",
      submitPlanned: "Post my request",
      reqPrefix: "Request",
      confTitle: "We're on it",
      confNotifying: (n: number, d: string) => `We're reaching out to ${n} artisans in ${d} right now`,
      confTargeted: "targeted artisans",
      confResponse: "usual first reply",
      confAccept: "You'll get a WhatsApp message as soon as someone confirms they can come",
      postAnother: "Post another request",
      expiryLabel: "Keep this request active for",
      expiryHint: "After that it closes automatically — you can always repost.",
      expiryDay: "day",
      expiryDays: "days",
    },
    dashboard: {
      tabJobs: "Jobs",
      tabProfile: "Profile",
      tabReviews: "Reviews",
      tabSettings: "Settings",
      statusOnline: "Open now",
      statusClosed: "Closed today",
      statusDeactivated: "Profile being set up",
      refresh: "Refresh",
      saveChanges: "Save changes",
      uploadPhotos: "Upload",
      choosePhotos: "Choose photos",
      releaseJob: "Release job",
      claimedJobsTitle: "My claimed jobs",
      claimedJobsDesc: "Jobs you've said yes to. If something comes up and you can't make it, tap Release so a client isn't left waiting.",
      targetedLeadsTitle: "Jobs matched to you",
      jobBoardTitle: "All available jobs near you",
      skillsLabel: "What work do you do?",
      workingHoursLabel: "When are you available?",
      portfolioLabel: "Portfolio showcase",
      accountStatusLabel: "Pause or deactivate your profile",
      deleteAccountLabel: "Delete account",
    },
  },
  fr: {
    nav: { postJob: "Obtenir de l'aide", login: "Connexion", artisan: "Vous etes artisan ?" },
    hero: {
      location: "Fait a Maurice",
      eyebrow: "Trouvez un artisan de confiance a Maurice — aujourd'hui",
      headlineLead: "Faites reparer par un",
      headlineEm: "artisan local de confiance",
      headlineTail: ".",
      support:
        "Dites-nous ce qui ne va pas, nous trouvons un artisan verifie pres de chez vous, et il vous contacte sur WhatsApp. Fini d'appeler cinq personnes en esperant que l'une reponde.",
      ctaPrimary: "Decrivez votre probleme — on trouve quelqu'un aujourd'hui",
      ctaSecondary: "Comment ca marche",
      chips: ["Artisans verifies", "Contact sur WhatsApp", "EN / FR / Kreol", "Le jour meme"],
      visualBadge: "Verifie",
      visualCaption: "Le plombier de votre voisin, en un clic",
    },
    how: {
      title: "Comment fonctionne Artizan Moris",
      subtitle: "Trois etapes, et fini de courir apres les artisans tout l'apres-midi.",
      steps: [
        { title: "Decrivez le travail", desc: "Deux phrases et une photo rapide depuis votre telephone — c'est tout." },
        { title: "Mise en relation avec des pros verifies", desc: "Nous prevenons les artisans proches qui font exactement ce travail." },
        { title: "Discutez et reservez sur WhatsApp", desc: "Chattez directement sur WhatsApp, convenez d'une heure qui vous convient, c'est regle." },
      ],
    },
    tradesSection: {
      title: "Metiers populaires",
      subtitle: "Tapez ce dont vous avez besoin — on s'occupe du reste.",
    },
    request: {
      eyebrow: "Commencez ici",
      title: "Dites-nous ce dont vous avez besoin",
      subtitle: "Postez une fois, soufflez. Les artisans verifies vous contactent sur WhatsApp — sans frais.",
    },
    why: {
      title: "Pourquoi Artizan Moris",
      items: [
        { title: "Artisans verifies", desc: "Chaque artisan est verifie avant d'apparaitre sur la plateforme." },
        { title: "Local a Maurice", desc: "Pense pour Maurice — les districts, les metiers, et oui, WhatsApp, parce que c'est comme ca qu'on communique tous." },
        { title: "Fini le week-end gache a chercher un plombier", desc: "Une seule demande claire atteint les bons artisans pour vous." },
        { title: "Gratuit a poster", desc: "Gratuit a poster, toujours. Vous parlez uniquement aux artisans que vous avez choisis." },
      ],
    },
    browse: {
      eyebrow: "Parcourir les artisans",
      title: "Artisans verifies",
      subtitle: "Filtrez par metier, region et service. Les profils verifies apparaissent en premier.",
      filters: "Filtres",
      quickTitle: "Departs rapides",
      filterAction: "Filtrer",
      resetAction: "Reinitialiser",
      searchPlaceholder: "Fuite, electricite, clim, meuble...",
      fastFirst: "Plus rapides",
      readyHeading: (n: number) => `${n} ${n === 1 ? "artisan pret" : "artisans prets"}`,
      sortedEta: "Tries par delai",
      verifiedFirst: "Verifies en premier",
      availableNow: (n: number) => `${n} disponibles`,
      onboarding: "De nouveaux artisans verifies nous rejoignent chaque semaine",
      fastestEta: (n: number) => `${n} min de delai le plus court`,
      etaSoon: "Le delai s'affiche des qu'il y a des correspondances",
      reviewAfter: "Notez votre artisan apres le travail",
      allVerified: "Tous les artisans verifies",
      emptyTitle: "On est encore en train de grandir dans votre zone",
      emptyCopy:
        "Nous inscrivons des artisans verifies partout sur l'ile en ce moment. Postez votre travail et nous vous mettrons en contact des que quelqu'un est disponible dans votre zone.",
      emptyCta: "Poster votre travail",
      view: "Voir",
      selected: "Selectionne",
      available: "Disponible",
      later: "Plus tard",
      verified: "Verifie",
      portfolio: "Portfolio",
      portfolioEmpty: "Les photos apparaitront ici une fois que l'artisan aura ajoute ses travaux verifies.",
      reviews: "Avis",
      reviewsCount: (n: number) =>
        n
          ? `${n} avis publics enregistres. Les commentaires detailles s'afficheront bientot.`
          : "Pas encore d'avis publics.",
      availability: "Disponibilite",
      availableToday: (n: number) => `Disponible aujourd'hui. Reponse estimee : ${n} min.`,
      notAvailable: "Pas disponible pour le moment. Vous pouvez quand meme preparer une demande.",
      selectHint: "Envoyez une demande prete pour WhatsApp directement a cet artisan.",
      whatsapp: "Contacter sur WhatsApp",
      whatsappBadge: "WhatsApp",
      callContact: "Appeler",
      reviewsNone: "Pas encore d'avis — soyez le premier.",
      leaveReview: "Laisser un avis",
      reviewName: "Votre nom",
      reviewNamePh: "ex. Reshad",
      reviewRatingLabel: "Votre note",
      reviewComment: "Votre avis",
      reviewCommentPh: "Comment etait le travail ?",
      reviewSubmit: "Envoyer l'avis",
      reviewSubmitting: "Envoi...",
      reviewThanks: "Merci ! Votre avis est publie.",
      noMatch: "Aucun resultat pour ces filtres",
      noMatchHint: "Essayez moins de filtres ou une autre recherche.",
    },
    faq: {
      title: "Bon a savoir",
      items: [
        { q: "Est-ce gratuit de poster un travail ?", a: "Oui. Poster un travail sur Artizan Moris est totalement gratuit. Vous reglez le paiement directement avec l'artisan choisi." },
        { q: "Comment les artisans me contactent ?", a: "Votre numero WhatsApp reste prive. Les artisans qui acceptent votre travail vous contactent via un lien protege — ils ne voient jamais votre numero directement." },
        { q: "Les artisans sont-ils verifies ?", a: "Chaque artisan est verifie avant d'etre propose, et les profils verifies sont clairement identifies." },
        { q: "Quelles regions couvrez-vous ?", a: "Tout Maurice, de Port-Louis a Rodrigues. Choisissez simplement la region la plus proche quand vous postez." },
        { q: "Et si personne n'est en ligne ?", a: "Nous sommes encore en train de grandir dans certaines regions. Postez quand meme — des qu'un artisan verifie arrive dans votre zone, il verra votre demande en premier." },
      ],
    },
    footer: {
      tagline: "Votre reference pour trouver un artisan fiable partout a Maurice.",
      cols: { product: "Produit", company: "Entreprise" },
      links: { post: "Poster un travail", browse: "Parcourir les artisans", artisan: "Devenir artisan", login: "Connexion" },
      contact: "Contact",
      builtFor: "Concu pour la recherche de services locaux",
    },
    bottomNav: { browse: "Artisans", request: "Poster", artisan: "Artisan", login: "Connexion" },
    jobForm: {
      steps: ["Urgence", "Probleme", "Lieu", "Contact"],
      badge: "Mise en relation",
      eyebrow: "Demande",
      title: "Trouver un artisan",
      urgentTitle: "J'ai besoin de quelqu'un aujourd'hui",
      urgentDesc: "Nous trouverons un artisan verifie pres de chez vous dans l'heure.",
      plannedTitle: "Je planifie a l'avance",
      plannedDesc: "Dites-nous le travail et les artisans verifies pres de chez vous prendront contact.",
      describeLabel: "C'est quoi le probleme ?",
      describePlaceholder: "ex. L'evier de la cuisine fuit depuis ce matin, de l'eau sous le meuble...",
      tradeLabel: "Quel type d'artisan cherchez-vous ? (touchez pour changer)",
      useLocation: "Utiliser ma position",
      locUnavailable: "Le GPS n'est pas disponible ici. Choisissez la region la plus proche.",
      locShared: "Position partagee. Choisissez la region la plus proche pour une mise en relation plus rapide.",
      locDenied: "Pas de souci — choisissez simplement votre zone dans la liste ci-dessous.",
      whatsappLabel: "Numero WhatsApp",
      privacy: "Votre numero WhatsApp reste prive. Les artisans vous contactent via l'app une fois qu'ils ont accepte — vous decidez a qui repondre.",
      addPhoto: "Ajouter une photo",
      photoHint: "Optionnel — une photo rapide aide les artisans a estimer le travail",
      errUrgency: "Dites-nous si c'est urgent — ca change comment on vous met en relation.",
      errDescription: "Un peu plus de detail aide les artisans a venir prepares — meme une phrase suffit.",
      errDistrict: "Choisissez votre zone pour qu'on sache quels artisans sont proches.",
      errPhone: "Verifiez votre numero — ca doit etre un mobile mauricien commencant par 5, 7 ou 8.",
      errPhotoType: "Veuillez choisir un fichier image.",
      errPhotoSize: "Cette photo est un peu grande. Essayez une capture d'ecran ou reduisez la taille — moins de 5 Mo ca marche.",
      errPost: "La demande n'a pas pu etre postee.",
      errFailed: "Un probleme de notre cote. Vos informations sont sauvegardees — tapez pour reessayer.",
      back: "Retour",
      continue: "Continuer",
      submitUrgent: "Envoyer ma demande maintenant",
      submitPlanned: "Poster ma demande",
      reqPrefix: "Demande",
      confTitle: "On s'en occupe",
      confNotifying: (n: number, d: string) => `Nous contactons ${n} artisans a ${d} en ce moment`,
      confTargeted: "artisans cibles",
      confResponse: "premiere reponse habituelle",
      confAccept: "Vous recevrez un message WhatsApp des que quelqu'un confirme pouvoir venir",
      postAnother: "Poster une autre demande",
      expiryLabel: "Garder cette demande active pendant",
      expiryHint: "Apres ca elle se ferme automatiquement — vous pouvez toujours reposter.",
      expiryDay: "jour",
      expiryDays: "jours",
    },
    dashboard: {
      tabJobs: "Travaux",
      tabProfile: "Profil",
      tabReviews: "Avis",
      tabSettings: "Parametres",
      statusOnline: "Ouvert maintenant",
      statusClosed: "Ferme aujourd'hui",
      statusDeactivated: "Profil en cours",
      refresh: "Actualiser",
      saveChanges: "Sauvegarder",
      uploadPhotos: "Telecharger",
      choosePhotos: "Choisir des photos",
      releaseJob: "Liberer le travail",
      claimedJobsTitle: "Mes travaux acceptes",
      claimedJobsDesc: "Travaux que vous avez acceptes. Si quelque chose se presente et que vous ne pouvez pas y aller, tapez Liberer pour ne pas laisser un client en attente.",
      targetedLeadsTitle: "Travaux qui matchent avec vous",
      jobBoardTitle: "Tous les travaux disponibles pres de chez vous",
      skillsLabel: "Quel travail faites-vous ?",
      workingHoursLabel: "Quand etes-vous disponible ?",
      portfolioLabel: "Portfolio",
      accountStatusLabel: "Mettre en pause ou desactiver votre profil",
      deleteAccountLabel: "Supprimer le compte",
    },
  },
  mfe: {
    nav: { postJob: "Gagn led zordi", login: "Konekte", artisan: "Ou enn artizan ?" },
    hero: {
      location: "Fer dan Moris",
      eyebrow: "Trouv enn artizan serye dan Moris — zordi mem",
      headlineLead: "Fer repare par enn",
      headlineEm: "artizan lokal serye",
      headlineTail: ".",
      support:
        "Dir nou ki finn kase, nou trouv enn artizan verifye pre kot ou, ek zot kontak ou lor WhatsApp. Nepli bizin apele sink moune pou espere ki enn repons.",
      ctaPrimary: "Dekrir ou problem — nou pou trouv enn moune zordi",
      ctaSecondary: "Kouma sa marse",
      chips: ["Artizan verifye", "Kontak lor WhatsApp", "EN / FR / Kreol", "Zordi mem"],
      visualBadge: "Verifye",
      visualCaption: "Plonbie ou vwazin, enn tap lwin",
    },
    how: {
      title: "Kouma Artizan Moris marse",
      subtitle: "Trwa step, ek fini gaspiy lapremidi antie pou rod artizan.",
      steps: [
        { title: "Dekrir travay-la", desc: "De fraz ek enn foto rapid depi ou telefonn — samem tou." },
        { title: "Gagn bann pro verifye", desc: "Nou averti bann artizan pre kot ou ki fer sa kalite travay-la." },
        { title: "Koz ek rezerv lor WhatsApp", desc: "Chat direk lor WhatsApp, tombe dakor lor enn ler ki konn ar zot de, fini." },
      ],
    },
    tradesSection: {
      title: "Metie popiler",
      subtitle: "Tap seki ou bizin — nou pran sarz leresto.",
    },
    request: {
      eyebrow: "Koumans isi",
      title: "Dir nou ki ou bizin",
      subtitle: "Poste enn sel fwa, repoze. Bann artizan verifye kontak ou lor WhatsApp — gartis.",
    },
    why: {
      title: "Kifer Artizan Moris",
      items: [
        { title: "Artizan verifye", desc: "Sak artizan verifye avan ki li paret lor plateform-la." },
        { title: "Lokal pou Moris", desc: "Fer pou Moris — distrik, metie, ek wi, WhatsApp, parski samem kouma nou tou komonike." },
        { title: "Fini gate wikenn pou rod plonbie", desc: "Enn sel demann prop ariv kot bann bon artizan." },
        { title: "Gartis pou poste", desc: "Gartis pou poste, toultan. Ou koz zis ar bann artizan ki ou finn swazir." },
      ],
    },
    browse: {
      eyebrow: "Get bann artizan",
      title: "Artizan verifye",
      subtitle: "Filtre par metie, landrwa ek servis. Bann profil verifye paret avan.",
      filters: "Filtre",
      quickTitle: "Koumans vit",
      filterAction: "Filtre rezilta",
      resetAction: "Reset",
      searchPlaceholder: "Fuit, kouran, klim, plakar...",
      fastFirst: "Pli vit avan",
      readyHeading: (n: number) => `${n} artizan pare`,
      sortedEta: "Trie par dele",
      verifiedFirst: "Verifye avan",
      availableNow: (n: number) => `${n} disponib la`,
      onboarding: "Plis artizan verifye pe zwenn nou sak semenn",
      fastestEta: (n: number) => `${n} min dele pli kourt`,
      etaSoon: "Dele paret kan ena bann korespondans",
      reviewAfter: "Note ou artizan apre travay",
      allVerified: "Tou bann artizan verifye",
      emptyTitle: "Nou ankor pe grandi dan ou landrwa",
      emptyCopy:
        "Nou pe anrezistre bann artizan verifye partou dan lil aster. Poste ou travay ek nou pou konekte ou deswit ki enn moune disponib dan ou landrwa.",
      emptyCta: "Poste ou travay",
      view: "Get",
      selected: "Swazir",
      available: "Disponib",
      later: "Plitar",
      verified: "Verifye",
      portfolio: "Portfolio",
      portfolioEmpty: "Bann foto pou paret isi kan artizan-la inn azout so travay verifye.",
      reviews: "Komanter",
      reviewsCount: (n: number) =>
        n
          ? `${n} komanter piblik. Bann detay pou paret biento.`
          : "Pena komanter piblik ankor.",
      availability: "Disponibilite",
      availableToday: (n: number) => `Disponib zordi. Repons estime: ${n} min.`,
      notAvailable: "Pa disponib la. Ou kapav prepar enn demann pou plitar.",
      selectHint: "Avoy enn demann pare pou WhatsApp direk ar sa artizan-la.",
      whatsapp: "Kontak lor WhatsApp",
      whatsappBadge: "WhatsApp",
      callContact: "Apele",
      reviewsNone: "Pena avis ankor — ou kapav premie.",
      leaveReview: "Les enn avis",
      reviewName: "Ou nom",
      reviewNamePh: "ex. Reshad",
      reviewRatingLabel: "Ou not",
      reviewComment: "Ou avis",
      reviewCommentPh: "Kouma travay-la ti ete?",
      reviewSubmit: "Avoy avis",
      reviewSubmitting: "Pe avoy...",
      reviewThanks: "Mersi! Ou avis afise.",
      noMatch: "Pena rezilta pou sa bann filtre-la",
      noMatchHint: "Esey mwins filtre ou enn lot rod.",
    },
    faq: {
      title: "Bon pou kone",
      items: [
        { q: "Eski gartis pou poste enn travay?", a: "Wi. Poste enn travay lor Artizan Moris net gartis. Ou aranz peyman direk ar artizan ki ou swazir." },
        { q: "Kouma bann artizan kontak mwa?", a: "Ou nimero WhatsApp res prive. Bann artizan ki aksepte ou travay kontak ou via enn lien protze — zot pa kapav get ou nimero direk." },
        { q: "Eski bann artizan verifye?", a: "Sak artizan verifye avan ki li kapav gagn enn travay, ek bann profil verifye ena enn badz kler." },
        { q: "Ki landrwa zot kouver?", a: "Tou Moris, depi Port-Louis ziska Rodrig. Swazir zis landrwa pli pre kan ou poste." },
        { q: "Ki arive si personn pa an liyn?", a: "Nou ankor pe grandi dan sertin landrwa. Poste kanmem — deswit ki enn artizan verifye an liyn dan ou landrwa, li pou trouv ou demann an premie." },
      ],
    },
    footer: {
      tagline: "Ou referans pou trouv enn artizan serye partou dan Moris.",
      cols: { product: "Prodwi", company: "Konpani" },
      links: { post: "Poste enn travay", browse: "Get bann artizan", artisan: "Vinn enn artizan", login: "Konekte" },
      contact: "Kontak",
      builtFor: "Fer pou trouv servis lokal",
    },
    bottomNav: { browse: "Artizan", request: "Poste", artisan: "Artizan", login: "Konekte" },
    jobForm: {
      steps: ["Urzans", "Problem", "Landrwa", "Kontak"],
      badge: "Smart match",
      eyebrow: "Demann",
      title: "Trouv enn artizan",
      urgentTitle: "Mo bizin enn moune zordi",
      urgentDesc: "Nou pou trouv enn artizan verifye pre kot ou dan enn ler.",
      plannedTitle: "Mo pe planifye",
      plannedDesc: "Dir nou travay-la ek bann artizan verifye pre kot ou pou kontak ou.",
      describeLabel: "Ki problem ou ena?",
      describePlaceholder: "ex. Robine lakwizinn pe koule depi gramatin, dilo anba meb...",
      tradeLabel: "Ki kalite artizan ou bizin? (tap pou sanze)",
      useLocation: "Servi mo pozisyon",
      locUnavailable: "GPS pa disponib isi. Swazir landrwa pli pre.",
      locShared: "Pozisyon partaze. Swazir landrwa pli pre pou enn mise an kontak pli vit.",
      locDenied: "Pa gagn traka — swazir zis ou landrwa dan laliste anba.",
      whatsappLabel: "Nimero WhatsApp",
      privacy: "Ou nimero WhatsApp res prive. Bann artizan kontak ou via lapp enn fwa ki zot aksepte — ou desid a ki ou reponn.",
      addPhoto: "Azout enn foto",
      photoHint: "Opsionel — enn foto rapid ed bann artizan estime travay-la",
      errUrgency: "Dir nou si sa urzan — sa sanze kouma nou match ou.",
      errDescription: "Enn tiginn plis detay ed bann artizan vini prepare — mem enn fraz sifi.",
      errDistrict: "Swazir ou landrwa pou nou kone ki artizan pre kot ou.",
      errPhone: "Verifye ou nimero — bizin enn mobil Morisien ki koumans ar 5, 7 ou 8.",
      errPhotoType: "Silvouple swazir enn fisye imaz.",
      errPhotoSize: "Sa foto-la enn tiginn gro. Esey enn screenshot ou redwir tay — nenpot kitsoz mwins ki 5 Mo marse.",
      errPost: "Demann pa finn kapav poste.",
      errFailed: "Enn problem lor nou bout. Ou bann info sove — tap pou reeesey.",
      back: "Retour",
      continue: "Kontinye",
      submitUrgent: "Avoy mo demann aster",
      submitPlanned: "Poste mo demann",
      reqPrefix: "Demann",
      confTitle: "Nou lor li",
      confNotifying: (n: number, d: string) => `Nou pe kontak ${n} artizan dan ${d} aster`,
      confTargeted: "artizan sible",
      confResponse: "premie repons abitiel",
      confAccept: "Ou pou resevwar enn mesaz WhatsApp deswit ki enn moune konfirm ki li kapav vini",
      postAnother: "Poste enn lot demann",
      expiryLabel: "Gard sa demann aktif pandan",
      expiryHint: "Apre sa li ferm otomatikman — ou kapav toultan reposte.",
      expiryDay: "zour",
      expiryDays: "zour",
    },
    dashboard: {
      tabJobs: "Travay",
      tabProfile: "Profil",
      tabReviews: "Komanter",
      tabSettings: "Seting",
      statusOnline: "Ouver la",
      statusClosed: "Ferme zordi",
      statusDeactivated: "Profil pe prepare",
      refresh: "Aktyalize",
      saveChanges: "Sov sanzman",
      uploadPhotos: "Telesarz",
      choosePhotos: "Swazir foto",
      releaseJob: "Libere travay",
      claimedJobsTitle: "Mo bann travay aksepte",
      claimedJobsDesc: "Travay ki ou finn aksepte. Si kitsoz arive ek ou pa kapav ale, tap Libere pou pa les enn kliyan atann.",
      targetedLeadsTitle: "Travay ki match ar ou",
      jobBoardTitle: "Tou bann travay disponib pre kot ou",
      skillsLabel: "Ki travay ou fer?",
      workingHoursLabel: "Kan ou disponib?",
      portfolioLabel: "Portfolio",
      accountStatusLabel: "Mete an paz ou dezaktive ou profil",
      deleteAccountLabel: "Efase kont",
    },
  },
};

export type Language = keyof typeof marketplaceCopy;

export const languageOptions: { value: Language; label: string }[] = [
  { value: "en", label: "EN" },
  { value: "fr", label: "FR" },
  { value: "mfe", label: "Morisien" },
];

export const tabLabels: Record<Language, { home: string; how: string; browse: string }> = {
  en: { home: "Home", how: "How it works", browse: "Browse artisans" },
  fr: { home: "Accueil", how: "Comment ca marche", browse: "Parcourir" },
  mfe: { home: "Akey", how: "Kouma sa marse", browse: "Get artizan" },
};

export const popularTrades: { value: string; icon: typeof Wrench; labels: Record<Language, string> }[] = [
  { value: "Plumber", icon: Wrench, labels: { en: "Plumber", fr: "Plombier", mfe: "Plonbie" } },
  { value: "Electrician", icon: PlugZap, labels: { en: "Electrician", fr: "Electricien", mfe: "Elektrisien" } },
  { value: "Painter", icon: PaintRoller, labels: { en: "Painter", fr: "Peintre", mfe: "Pintur" } },
  { value: "Carpenter", icon: Hammer, labels: { en: "Carpenter", fr: "Menuisier", mfe: "Menwizie" } },
  { value: "Mason", icon: HardHat, labels: { en: "Mason", fr: "Macon", mfe: "Mason" } },
  { value: "AC technician", icon: Snowflake, labels: { en: "AC technician", fr: "Climatisation", mfe: "Klimatizasion" } },
  { value: "Locksmith", icon: KeyRound, labels: { en: "Locksmith", fr: "Serrurier", mfe: "Serurie" } },
  { value: "Gardener", icon: Leaf, labels: { en: "Gardener", fr: "Jardinier", mfe: "Zardinie" } },
];

export const heroStats: { value: number; suffix: string; labels: Record<Language, string> }[] = [
  { value: 8, suffix: "", labels: { en: "Trades", fr: "Metiers", mfe: "Metie" } },
  { value: 9, suffix: "", labels: { en: "Districts", fr: "Districts", mfe: "Distrik" } },
  { value: 100, suffix: "%", labels: { en: "Free to post", fr: "Gratuit", mfe: "Gartis" } },
];

export const heroShowcase: { trade: string; image: string; tilt: string; float: string; delay: string }[] = [
  { trade: "Plumber", image: tradeImages.Plumber, tilt: "-4deg", float: "animate-float", delay: "" },
  { trade: "Electrician", image: tradeImages.Electrician, tilt: "5deg", float: "animate-float-slow", delay: "anim-delay-2" },
  { trade: "Carpenter", image: tradeImages.Carpenter, tilt: "-3deg", float: "animate-float-soft", delay: "anim-delay-1" },
];

export const quickFilters = [
  { label: "Pipe leak", query: "leak", trade: "Plumber", tag: "Leak repair" },
  { label: "No power", query: "wiring", trade: "Electrician", tag: "No power" },
  { label: "Emergency repair", query: "urgent repair", trade: allTradesLabel, tag: "Emergency repair" },
  { label: "AC service", query: "ac service", trade: "AC technician", tag: "AC service" },
  { label: "Door lock", query: "door lock", trade: "Locksmith", tag: allTagsLabel },
  { label: "Paint room", query: "paint", trade: "Painter", tag: "Renovation" },
];

export const tradeSearchAliases: Record<string, string[]> = {
  Plumber: ["plumber", "plombier", "leak", "fuite", "water", "pipe", "sink", "drain", "robinet"],
  Plombier: ["leak", "fuite", "water", "pipe", "sink", "drain", "robinet"],
  Electrician: ["electrician", "electricien", "wiring", "electric", "power", "light", "prise", "breaker", "circuit"],
  Electricien: ["wiring", "electric", "power", "light", "prise", "breaker", "circuit"],
  Mason: ["mason", "macon", "wall", "concrete", "block", "tiles", "renovation", "repair"],
  Macon: ["wall", "concrete", "block", "tiles", "renovation", "repair"],
  Carpenter: ["carpenter", "menuisier", "cabinet", "cupboard", "door", "wood", "kitchen", "shelf"],
  Menuisier: ["cabinet", "cupboard", "door", "wood", "kitchen", "shelf"],
  "AC technician": ["ac", "aircon", "clim", "split", "cooling", "maintenance"],
  Climatisation: ["ac", "aircon", "clim", "split", "cooling", "maintenance"],
  Painter: ["painter", "peintre", "paint", "painting", "repaint", "wall finish", "color"],
  Peintre: ["paint", "painting", "repaint", "wall finish", "color"],
  Gardener: ["gardener", "jardinier", "garden", "grass", "yard", "tree", "plants", "trim"],
  Jardinier: ["garden", "grass", "yard", "tree", "plants", "trim"],
  Locksmith: ["locksmith", "serrurier", "lock", "key", "door lock", "locked", "security"],
  Serrurier: ["lock", "key", "door lock", "locked", "security"],
};
